export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',

  AGENCY_ADMIN = 'AGENCY_ADMIN',
  AGENCY_MANAGER = 'AGENCY_MANAGER',
  AGENCY_FINANCIAL = 'AGENCY_FINANCIAL',
  AGENCY_FREIGHT_ORGANISER = 'AGENCY_FREIGHT_ORGANISER',
  AGENCY_DRIVER_WAREHOUSE = 'AGENCY_DRIVER_WAREHOUSE',

  PARTNER_ADMIN = 'PARTNER_ADMIN',
  PARTNER_MANAGER = 'PARTNER_MANAGER',
  PARTNER_FINANCIAL = 'PARTNER_FINANCIAL',
  PARTNER_FREIGHT_ORGANISER = 'PARTNER_FREIGHT_ORGANISER',
  PARTNER_DRIVER_WAREHOUSE = 'PARTNER_DRIVER_WAREHOUSE',
}
