export enum AppRoutes {
  LOGIN = 'login',
  STATS = 'stats',
  COMPANY = 'company',
  MY_COMPANY = 'my-company',
  PARTNERS = 'partners',
  CONTACTS = 'contacts',
  DETAILS = 'details',
  EMPLOYEES = 'employees',
  PREMISES = 'premises',
  VEHICLES = 'vehicles',
  LINEMANAGEMENT = 'line-management',
  LINEORGANIZATION = 'line-organization',
  LINELIST = 'line-list',
  LINE = 'line',
  STATIONS = 'stations',
  MAP = 'map',
  CONSIGNMENT = 'consignment',
  CONSIGNMENTS = 'consignments',
  OFFER = 'offer',
  PARCEL = 'parcel',
  DOCUMENTS = 'documents',
  STATUSES = 'statuses',
  SETTINGS = 'settings',
  ORDER = 'order',
  NOTIFICATION = 'notifications'
}
